# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ENV["development_secret_key_base"]

test:
  secret_key_base: ENV["test_secret_key_base"]

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
